# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
sudo: false
cache: packages
addons:
  apt:
    packages:
    - libhdf5-dev
    - mesa-common-dev
    - libglu1-mesa-dev
env:
  global:
    - RGL_USE_NULL=TRUE
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
