# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
sudo: required
cache: packages
addons:
  apt:
    packages:
    - libhdf5-dev
    - mesa-common-dev
    - libglu1-mesa-dev
env:
  global:
    - RGL_USE_NULL=TRUE

apt_packages:
  - r-cran-rjava
before_install:
  - sudo $(which R) CMD javareconf
  - Rscript -e 'remotes::install_github("r-lib/pkgdown")'

before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: true
